{% set name = "csv_extract" %}
{% set version = "1.0" %}
{% set sha256 = "YOUR_CHECKSUM_FROM_THE_TAR_GZ_FILE" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # This now points to the public, raw source code archive on GitHub
  url: https://github.com/nathnael-desta/galaxy_column_extractor_tool/raw/main/csv_extract-1.0.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  commands:
    - csv_extract --version

about:
  home: https://github.com/nathnael-desta/galaxy_column_extractor_tool
  license: MIT
  summary: "Extracts specific columns from a CSV file."
